export var swapForm = {
        currencyPair: 'USD/CNY',
        tradingType: '掉期',
        yuanDuanMaiMaiFanagxiang: '卖出外币',
        tradingDate: Date.now(),
        currency1InterestCurve: '美元隐含利率曲线',
        currency2InterestCurve: '人名币FR007收益利率曲线',
        intepolationType: '线性插值',
        jiXiTianShuFangshi: 'ACT/365',
        yingYeRiGuiZe: '调整至下一营业日',
        jinDuanHuiLv: 6542.1,
        yuanDuanHuiLv: 6.5421,
        jinDuanQiXiRi:  Date.now(),
        jinDuanJiaoGeRi:  Date.now(),
        waiBiJinDuanJingE: 1000,
        waiBiJinDuanLiLv: 0.0201,
        benBiJinDuanJingE: 6542.1,
        benBiJinDuanLiLv: 0.021,
        waiBiYuanDuanJingE: 6555.2,
        waiBiYuaDuanLiLv: 0.0350,
        benBiYuaDuanJingE: 100,
        benBiYuaDuanLiLv: 0.024,
        yuanDuanQixiRi: Date.now(),
        yuanDuanJiaogeRi: Date.now(),
        waiBiLiLvCurve:'美元隐含利率曲线',
        benBiLiLvCurve:'人名币FR007收益利率曲线',
}

export var swapFormResult = {
       PV1: '0',
        PV2: '0',
        NPV: '0',
        calcUnit:'CYN',
        PV1Taoli: '0',
        PV2Taoli: '0',
        NPVTaoli: '0',
        taoLiKongJian:'0',
        calcTaoliUnit:'CYN'
}

export var europeanResultDeltaHedge={
        spotHedge:'',
        forwardHedge:'',
        currencyUnit:'CNY'
}
export var europeanResultVegaHedge={
        option1Type:'',
        option2Type:'',
        option1Amount:'',
        option2Amount:'',
        currencyUnit:'CNY'
}

export var europeanResultLeg1={
        NPV:'',
        Delta:'',
        Gamma:'',
        Vega:'',
        Theta:'',
        Rho:'',
}
export var europeanResultLeg2={
        NPV:'',
        Delta:'',
        Gamma:'',
        Vega:'',
        Theta:'',
        Rho:'',
}
export var europeanOptionLeg1Form={
        currencyPair:'USD/CNY',
        direction:'Buy',
        optionType:'Call',
        tradeDate: Date.now(),
        expireDate: Date.now(),
        jiaoGeDate: Date.now(),
        benbiQiQuanJingE:'',
        waibiQiQuanJingE:'',
        volatility:'0.01987',
        xingQuanJia:'',
        qiQuanFei:'',
        jiXiTianShuFangshi: 'ACT/365',
        yingYeRiGuiZe: '调整至下一营业日',
        boDonglvQuMianChaZhi:'Linear of delta',
        zheXianQuxianChaZhi:'Linear log normal',
        waiBiLiLvCurve:'美元隐含利率曲线',
        benBiLiLvCurve:'人名币FR007收益利率曲线',
        benBiDaoQiYuanQiLiLv:'',
        waiBiDaoQiYuanQiLiLv:'',
    }
export var europeanOptionLeg2Form={
        currencyPair:'USD/CNY',
        direction:'Buy',
        optionType:'Call',
        tradeDate: Date.now(),
        expireDate: Date.now(),
        jiaoGeDate: Date.now(),
        benbiQiQuanJingE:'',
        waibiQiQuanJingE:'',
        volatility:'0.01987',
        xingQuanJia:'',
        qiQuanFei:'',
        jiXiTianShuFangshi: 'ACT/365',
        yingYeRiGuiZe: '调整至下一营业日',
        boDonglvQuMianChaZhi:'Linear of delta',
        zheXianQuxianChaZhi:'Linear log normal',
        waiBiLiLvCurve:'美元隐含利率曲线',
        benBiLiLvCurve:'人名币FR007收益利率曲线',
        benBiDaoQiYuanQiLiLv:'',
        waiBiDaoQiYuanQiLiLv:'',
    }

export var irsccsFormLeg1 = {
    direction: '收取利息',
    Amount: '',
    biZhong: '美元',
    xiPiaoLeiXing: '固定',
    fuXiPingLv: '1M',
    jiXiFangShi: '单利',
    xiPiaoLv: '0.05',
    xiPiaoLvChengShu: '1',
    shouCiFuXiRi: Date.now(),
    liCha: '5bp',
    weiciFuxiRi: Date.now(),
    canKaoLiLv: 'Libor',
    dingPanRiTiaoZheng: '2D',
    jiXiJiZhun: 'ACT/365',
    yingYeRiTiaoZheng: '调整至下一营业日',
    jieJiaRi: '北京',
    guZhiRi: Date.now(),
    qiXiRi: Date.now(),
    daoQiRi: Date.now(),
}
export var irsccsFormLeg2 = {
    direction: '支付利息',
    Amount: '',
    biZhong: '人民币',
    xiPiaoLeiXing: '固定',
    fuXiPingLv: '1M',
    jiXiFangShi: '单利',
    xiPiaoLv: '0.05',
    xiPiaoLvChengShu: '1',
    shouCiFuXiRi: Date.now(),
    liCha: '5bp',
    weiciFuxiRi: Date.now(),
    canKaoLiLv: 'Libor',
    dingPanRiTiaoZheng: '2D',
    jiXiJiZhun: 'ACT/365',
    yingYeRiTiaoZheng: '调整至下一营业日',
    jieJiaRi: '北京',
    guZhiRi: Date.now(),
    qiXiRi: Date.now(),
    daoQiRi: Date.now(),
}

export var irsccsResultForm = {
    NPV: '1',
    DV01: '1',
    yinJiLiXi: '',
    NPVLeg1: '1',
    DV01Leg1: '1',
    yinJiLiXiLeg1: '',
    NPVLeg2: '1',
    DV01Leg2: '1',
    yinJiLiXiLeg2: '',
    calculationTarget: 'NPV',
}

export var bondForm={
    jiXiTianShuFangshi:'ACT/365',
        yingYeRiGuiZe:'调整至下一营业日',
        zhaiQuanShouYiLvQuXianMingCheng:'中债企业债到期收益率曲线',
        jiZhunLiLvCanKaoQuXian:'人民币FR007收益曲线',
        zhaiQuanZheXianQuXian:'曲线名称',
        bondCode:'112074.SZ',
        bondRating:'AA-',
        remainingDate:'1.72Y',
        interestStartDate:Date.now(),
        exerciseDate:Date.now(),
        shouYiLv:'0.05176',
        piaoMianZongE:'1000',
        guZhiRi:Date.now(),
        zhaiQuanJianCheng:'',
        piaoMianLiLv:'',
        liLvFangShi:'固定',
        jieSuanRi:Date.now(),
        duiFuRi:Date.now(),
        liCha:'10',
        jieSuanJingE:'1035203.4795',
        shouCiJiZhunLiLvChongZhiRi:Date.now(),
        jiZhunLiLvChongZhiPingLv:'',
        fuDongLiLvCha:'10',
        fuDongLiLvBeiShu:'1',
        fuDongLiLvShangXian:'11',
        fuDongLiLvXiaXian:'1',
        jixiRiTiaoZheng:'1D',
        fuxiRiTiaoZheng:'1',
        fuXiPinLV:'按季度',
        jiZhunLiLv:'',
}
export var bondResultForm={
        quanJia:'',
        maishiJiuQi:'',
        jingJia:'',
        xiuZhengJiuQi:'',
        yingJiLiXi:'',
        DV01:'',
        tuXing:'',
        VaR:'',
}
export var swaptionForm= {
        touCun:'10000',
        jiaoYiLeiXing:'1Y',
        jiaoGeRi:Date.now(),
        qiXiRi:Date.now(),
        daoQiRi:Date.now(),
        tongZhiQiXian:'0D',
        jiaoYiDuiShou:'平安国际',
        biZhong:'人民币',
        xingQuanJia:'',
        jiaoGeFangShi:'本金交割',
        qiQuanFei:0.00,
        qiQuanFeiJiaoFuRi:'',
        guZhiRi:Date.now(),
        qiQuanGuZhiMoXing:'Black-Scholes',
        boDongLvLeXing:'Lognormal',
        piaoMianLiLv: '',
        zhiFuPingLv:'按季度',
        jiXiTianShuFangshi:'ACT/365',
        yingYeRiGuiZe:'调整至下一营业日',
        guaGouZhiShu:'',
        fuDongLiLvLiCha:'',
        gangGanLv:'',
        chongZhiPinLv:'按季度',
        zhiFuPingLvFuDongDuan:'按年',
        jiXiTianShuFangShiFuDongDuan:'ACT/365',
        zheXianQuXian:'',
        yuanQiQuXian:'',
        boDongLvQuMian:''

}
export var swaptionResultForm={
        pingZhiXingQuanJia:'',
        NPV:'',
        DV01:'',
        NPVWuFeiYong:'',
        qiQuanFei:'',
        Gamma:'',
        Vega:'',
        Theta:'',
        shouYiLv:'',
        yinHanBoDongLv:'',
}
export var digitaloptionForm={
    guZhiRi:Date.now(),
        currencyPair:'USD/CNY',
        digitalOptionType:'',
        qiXiRi:Date.now(),
        benBiJingE:'',
        maiMaiFangXiang:'买入外币',
        jiaoGeRi:Date.now(),
        waiBiJinE:'',
        optionDirection:'买入外币',
        daoQiRi:Date.now(),
        xingQuanJia:1.1,
        yingYeRiGuiZe:'调整至下一营业日',
        jiXiTianShuFangshi:"调整至下一营业日",
        benBiDaoQiYuanQiLiLv:'',
        waiBiDaoQiYuanQiLiLv:'',
        waiBiDaoJiQiJiaGe:'0'
}
export var digitaloptionResultForm={
    NPV:'0',
        Vega:'0',
        Delta:'0',
        Theta:'0',
        Gamma:'0',
        Rho1:'0',
        Rho2:'0',
}
